backend:
  name: github
  repo: sncoguzhansnc/celik-iplik
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "site_icerik"
    label: "Site Yazıları"
    folder: "data"
    create: true
    format: "json"
    fields:
      - {label: "Site Başlığı", name: "title", widget: "string"}
      - {label: "Hakkımızda Metni", name: "about_text", widget: "text"}
