backend:
  name: github
  repo: sncoguzhansnc/celikiplik
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "ayarlar"
    label: "Site Ayarları ve İletişim"
    files:
      - label: "Ana Sayfa Yazıları"
        name: "genel"
        file: "data/ayarlar.json"
        fields:
          - {label: "Site Ana Başlığı", name: "title", widget: "string"}
          - {label: "Ana Sayfa Karşılama Sloganı", name: "slogan", widget: "string"}
          - {label: "Hakkımızda Metni", name: "about_text", widget: "text"}
      - label: "İletişim Bilgileri"
        name: "iletisim"
        file: "data/iletisim.json"
        fields:
          - {label: "Telefon Numarası", name: "telefon", widget: "string"}
          - {label: "E-posta Adresi", name: "email", widget: "string"}
          - {label: "Adres", name: "adres", widget: "text"}

  - name: "urunler_koleksiyonu"
    label: "İplik Çeşitleri (Ürünler)"
    files:
      - label: "Tüm Ürünler Listesi"
        name: "urunler"
        file: "data/urunler.json"
        fields:
          - label: "Ürün Ekle"
            name: "urun_listesi"
            widget: "list"
            fields:
              - {label: "Ürün Adı", name: "urun_adi", widget: "string"}
              - {label: "Kısa Açıklama", name: "aciklama", widget: "text"}
